// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:medicine_reminder_app/models/emergency_contact.dart';
import 'package:medicine_reminder_app/models/medicine.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(EmergencyContactAdapter());
    registerAdapter(MedicineAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(EmergencyContactAdapter());
    registerAdapter(MedicineAdapter());
  }
}
